import type { LandingStat, FAQItem } from '@/lib/types/settings';

export const settingsDefaults: Record<string, unknown> = {
  'ai.model': 'gpt-5.2',
  'ai.temperature': 0.7,
  'ai.max_tokens': 16000,
  'ai.quality_model': 'gpt-4o-mini',
  'ai.quality_temperature': 0.3,
  'compliance.enabled': true,
  'compliance.state': 'MT',
  'compliance.max_description_length': 1000,
  'compliance.categories': [
    'steering', 'familial-status', 'disability', 'race-color-national-origin',
    'religion', 'sex-gender', 'age', 'marital-status', 'creed',
    'economic-exclusion', 'misleading-claims', 'military-status',
  ],
  'landing.hero_title_prefix': 'Ad',
  'landing.hero_title_accent': 'Drop',
  'landing.hero_tagline': 'Your Listing. 12 Platforms. Minimal Effort.',
  'landing.hero_description': 'Create a free account, enter your property details, and get a complete ad campaign — Instagram, Facebook, Google, print, direct mail. Typically ready in a few minutes, depending on listing complexity.',
  'landing.hero_cta': 'Start Creating — Free',
  'landing.stats': [
    { value: '12+', label: 'Ad Platforms' },
    { value: '3', label: 'Tone Options' },
    { value: 'Ads Are', label: 'Compliance Scanned' },
    { value: 'Minutes', label: 'Not Hours' },
  ] as LandingStat[],
  'landing.faq': [
    { question: 'Is AdDrop really free?', answer: 'Yes — AdDrop is completely free during beta. Create a free account, get 2 campaigns per week, and never see a credit card form.' },
    { question: 'Why do I need an account?', answer: 'Your account lets us save your campaigns, track your usage, and give you a dashboard to manage everything. Sign up with email and password. No credit card, no commitments.' },
    { question: 'What information do I need to get started?', answer: 'Just your property address, a few photos, and basic details like beds, baths, and price. AdDrop handles the rest.' },
    { question: 'How does the AI know what to write?', answer: "AdDrop's AI is designed for real estate marketing workflows. It understands platform best practices, character limits, tone variations, and fair housing compliance. It writes ads designed to sound polished and professional." },
    { question: 'Is the ad copy compliant with fair housing laws?', answer: 'AdDrop includes built-in compliance checking that helps identify and suggests corrections for problematic language. Currently supports Montana and Ohio MLS requirements, with more states planned.' },
    { question: 'Can I edit the generated ads?', answer: 'Absolutely. Every ad is fully editable. Use the AI output as a starting point and customize it to match your voice and brand.' },
    { question: 'What platforms are supported?', answer: "Instagram, Facebook, Google Ads, Twitter/X, Zillow, Realtor.com, print ads, direct mail postcards, magazine ads, and more. We're adding new platforms regularly." },
  ] as FAQItem[],
  'landing.cta_headline': 'Your Next Listing Deserves Better Marketing',
  'landing.cta_text': 'Create Your First Campaign',
  'landing.cta_beta': 'Free during beta. 2 campaigns per week. No credit card required.',
  'presets.default': [
    {
      name: 'Flathead Luxury Lakefront',
      listing_data: {
        url: '',
        address: { street: '1234 Lakeside Dr', city: 'Bigfork', state: 'MT', zip: '59911' },
        price: 1250000,
        beds: 4,
        baths: 3,
        sqft: 3200,
        propertyType: 'Single Family',
        features: ['Lakefront', 'Mountain views', 'Private dock', 'Gourmet kitchen'],
        description: 'Stunning lakefront estate on Flathead Lake with panoramic mountain views, private dock, and luxury finishes throughout.',
        photos: [
          '/images/properties/flathead-lakefront.png',
          '/images/properties/flathead-lake-1.png',
          '/images/properties/flathead-lake-2.png',
          '/images/properties/luxury-estate.png',
        ],
        listingAgent: 'Sarah Mitchell',
        broker: 'Glacier Sotheby\'s International Realty',
      },
      bestFor: ['instagram', 'metaAd', 'magazineFullPage'],
    },
    {
      name: 'Montana Mountain Cabin',
      listing_data: {
        url: '',
        address: { street: '789 Timber Trail', city: 'Whitefish', state: 'MT', zip: '59937' },
        price: 675000,
        beds: 3,
        baths: 2,
        sqft: 1800,
        propertyType: 'Cabin',
        features: ['Mountain views', 'Wood fireplace', 'Covered deck', 'National forest access'],
        description: 'Charming mountain cabin near Whitefish Mountain Resort with stunning views and year-round outdoor recreation.',
        photos: [
          '/images/properties/mountain-cabin.png',
          '/images/properties/mountain-vista.png',
          '/images/properties/mountain-lake.png',
          '/images/properties/mountain-lodge.png',
        ],
        listingAgent: 'Jake Thompson',
        broker: 'PureWest Real Estate',
      },
      bestFor: ['instagram', 'postcard', 'magazineFullPage'],
    },
    {
      name: 'Downtown Whitefish Commercial',
      listing_data: {
        url: '',
        address: { street: '102 Central Ave', city: 'Whitefish', state: 'MT', zip: '59937' },
        price: 895000,
        beds: 0,
        baths: 2,
        sqft: 4500,
        propertyType: 'Commercial',
        features: ['Downtown location', 'Street frontage', 'High visibility', 'Recently renovated'],
        description: 'Prime downtown Whitefish commercial space on Central Avenue with excellent foot traffic and visibility.',
        photos: [
          '/images/properties/downtown-mainstreet.png',
          '/images/properties/commercial-storefront.png',
          '/images/properties/commercial-restaurant.png',
        ],
        listingAgent: 'Lisa Reynolds',
        broker: 'Whitefish Realty Group',
      },
      bestFor: ['facebook', 'magazineFullPage'],
    },
    {
      name: 'Classic Montana Home',
      listing_data: {
        url: '',
        address: { street: '456 Elm Street', city: 'Kalispell', state: 'MT', zip: '59901' },
        price: 425000,
        beds: 4,
        baths: 2,
        sqft: 2100,
        propertyType: 'Single Family',
        features: ['Large yard', 'Updated kitchen', 'Hardwood floors', 'Two-car garage'],
        description: 'Well-maintained family home in a quiet Kalispell neighborhood with modern updates and spacious yard.',
        photos: [
          '/images/properties/classic-home-1.png',
          '/images/properties/classic-home-2.png',
          '/images/properties/classic-home-3.png',
          '/images/properties/classic-home-4.png',
        ],
        listingAgent: 'Mike Johnson',
        broker: 'National Parks Realty',
      },
      bestFor: ['facebook', 'postcard', 'googleAds'],
    },
  ],
};
