import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Disclaimer — AdDrop',
}

export default function DisclaimerPage() {
  return (
    <>
      {/*
        @generated-by: legal-pages
        @generated-date: 2026-02-12
        @jurisdictions: global-baseline, us-general
        @page-type: disclaimer
        @skill-version: 1.0
        Not legal advice — review with a lawyer for production use.
      */}

      <h1>Disclaimer</h1>
      <p><strong>Effective date:</strong> February 12, 2026</p>

      <p>
        This Disclaimer applies to the AdDrop platform and all content generated by or
        available through our service. Please read it carefully.
      </p>

      <h2>1. AI-Generated Content</h2>
      <p>
        AdDrop uses artificial intelligence (OpenAI) to generate advertising copy and
        marketing materials based on property data you provide. It is important to
        understand:
      </p>
      <ul>
        <li>
          <strong>AI-generated content is not professional marketing advice.</strong> The ad
          copy, headlines, descriptions, and other content generated by AdDrop are produced
          by artificial intelligence and are intended as a starting point for your marketing
          efforts.
        </li>
        <li>
          <strong>You must review all generated content</strong> before using it in any
          marketing campaign, advertisement, or publication. AI-generated content may contain
          inaccuracies, inappropriate language, or statements that do not comply with
          applicable advertising regulations.
        </li>
        <li>
          <strong>You are solely responsible</strong> for any content you publish or
          distribute, even if it was generated by AdDrop. This includes compliance with fair
          housing laws, truth-in-advertising requirements, MLS rules, real estate commission
          regulations, and any other applicable laws.
        </li>
        <li>
          <strong>We do not guarantee</strong> the accuracy, quality, effectiveness, or
          suitability of AI-generated content for any particular purpose.
        </li>
      </ul>

      <h2>2. No Professional Advice</h2>
      <p>
        AdDrop is a software tool, not a marketing agency, law firm, or licensed real estate
        advisor. The service does not constitute:
      </p>
      <ul>
        <li>Professional marketing or advertising advice</li>
        <li>Legal advice regarding advertising compliance</li>
        <li>Real estate industry guidance</li>
        <li>Endorsement of any marketing strategy</li>
      </ul>
      <p>
        You should consult qualified professionals (marketing consultants, attorneys,
        compliance officers) before launching any advertising campaign, particularly
        regarding fair housing regulations and advertising compliance requirements.
      </p>

      <h2>3. No Guarantee of Results</h2>
      <p>
        We make no representations or warranties about the effectiveness of any ad campaign
        created using AdDrop. Results depend on numerous factors beyond our control,
        including but not limited to:
      </p>
      <ul>
        <li>Market conditions and property characteristics</li>
        <li>Ad platform algorithms and policies</li>
        <li>Your advertising budget and targeting</li>
        <li>Local market competition</li>
        <li>The accuracy and quality of property data you provide</li>
      </ul>
      <p>Past examples or demonstrations do not guarantee future results.</p>

      <h2>4. Real Estate Advertising Compliance</h2>
      <p>
        Real estate advertising is subject to specific federal, state, and local regulations,
        including but not limited to:
      </p>
      <ul>
        <li>
          <strong>Fair Housing Act</strong> — prohibits discriminatory language in housing
          advertisements
        </li>
        <li>
          <strong>State real estate commission rules</strong> — may require specific
          disclosures in ads
        </li>
        <li>
          <strong>MLS rules</strong> — may govern how listing data can be used in advertising
        </li>
        <li>
          <strong>Truth-in-advertising laws</strong> — require that ad claims be truthful and
          substantiated
        </li>
      </ul>
      <p>
        AdDrop does not guarantee that AI-generated content complies with these regulations.{' '}
        <strong>It is your responsibility</strong> to review all content for compliance
        before publication.
      </p>

      <h2>5. External Links</h2>
      <p>
        Our service may contain links to third-party websites or resources. We have no
        control over the content or practices of those sites and accept no responsibility
        for them. The inclusion of any link does not imply endorsement by AdDrop.
      </p>

      <h2>6. Errors and Omissions</h2>
      <p>
        While we strive to provide accurate and reliable AI-generated content, errors,
        inaccuracies, and omissions may occur. We reserve the right to correct errors and
        update the service at any time without prior notice. We are not obligated to update
        or correct any content.
      </p>

      <h2>7. Limitation of Liability</h2>
      <p>
        Under no circumstances shall AdDrop be liable for any direct, indirect, incidental,
        special, consequential, or punitive damages arising from your use of, or inability
        to use, AI-generated content or any other aspect of the service. For full limitation
        of liability terms, please see our <Link href="/terms">Terms of Service</Link>.
      </p>

      <h2>8. Contact Us</h2>
      <p>
        If you have questions about this Disclaimer, contact us at:
      </p>
      <p>
        Email: <a href="mailto:support@addrop.com">support@addrop.com</a>
      </p>
    </>
  )
}
