import { ListingData } from '@/lib/types/listing';
import { PlatformId } from '@/lib/types/campaign';

export const SAMPLE_PROPERTIES: ListingData[] = [
  {
    url: '',
    address: {
      street: '8420 E Chaparral Rd',
      city: 'Scottsdale',
      state: 'AZ',
      zip: '85250',
      neighborhood: 'McCormick Ranch',
    },
    price: 1_195_000,
    beds: 5,
    baths: 4,
    sqft: 4200,
    lotSize: '0.31 acres',
    yearBuilt: 2018,
    propertyType: 'Single Family Home',
    features: [
      'Resort-style pool & spa',
      'Gourmet chef\'s kitchen with quartz countertops',
      'Primary suite with spa bath and walk-in closet',
      'Three-car garage with epoxy floors',
      'Open-concept great room with 12-ft ceilings',
      'Outdoor kitchen and covered patio',
      'Smart home automation system',
      'Solar panels (owned)',
    ],
    description:
      'Stunning modern luxury home in the heart of McCormick Ranch. This architectural masterpiece features soaring ceilings, walls of glass, and seamless indoor-outdoor living. The chef\'s kitchen boasts Wolf appliances, a 10-ft island, and custom cabinetry. Retreat to the primary suite complete with a spa-inspired bath and dual walk-in closets. The resort-style backyard with pool, spa, and outdoor kitchen is an entertainer\'s dream. Located minutes from top-rated schools, Scottsdale Quarter, and the 101.',
    photos: [],
    listingAgent: 'Sarah Mitchell',
    broker: 'Russ Lyon Sotheby\'s International Realty',
    mlsNumber: 'MLS6712345',
    sellingPoints: [
      'Luxury finishes throughout — no detail overlooked',
      'Owned solar panels for significant energy savings',
      'Walk to McCormick Ranch Golf Club',
      'Top-rated Scottsdale Unified School District',
      'Minutes from Fashion Square and Old Town Scottsdale',
    ],
  },
  {
    url: '',
    address: {
      street: '1845 Market St',
      city: 'Denver',
      state: 'CO',
      zip: '80202',
      neighborhood: 'LoDo',
    },
    price: 285_000,
    beds: 2,
    baths: 1,
    sqft: 950,
    yearBuilt: 2005,
    propertyType: 'Condominium',
    features: [
      'Floor-to-ceiling windows with city views',
      'Updated kitchen with stainless steel appliances',
      'In-unit washer/dryer',
      'Secure underground parking',
      'Rooftop deck with mountain views',
      'Concierge service',
      'Gym and fitness center',
      'Steps from Union Station',
    ],
    description:
      'Urban living at its finest in the heart of LoDo. This bright and airy 2-bedroom condo features floor-to-ceiling windows showcasing Denver\'s skyline. The open-concept layout maximizes the space with a modern kitchen, updated bath, and in-unit laundry. Building amenities include a rooftop deck with Rockies views, fitness center, and 24-hour concierge. Walk to Union Station, Coors Field, and Denver\'s best restaurants and nightlife.',
    photos: [],
    listingAgent: 'Marcus Chen',
    broker: 'LIV Sotheby\'s International Realty',
    mlsNumber: 'MLS4823901',
    sellingPoints: [
      'Prime LoDo location — walk everywhere',
      'Incredible value for a 2BR in downtown Denver',
      'Rooftop deck with panoramic mountain and city views',
      'Secure parking included in HOA',
      'Perfect lock-and-leave lifestyle',
    ],
  },
  {
    url: '',
    address: {
      street: '14230 Ballantyne Crossing Ave',
      city: 'Charlotte',
      state: 'NC',
      zip: '28277',
      neighborhood: 'Ballantyne',
    },
    price: 520_000,
    beds: 3,
    baths: 2,
    sqft: 2100,
    lotSize: '0.22 acres',
    yearBuilt: 2014,
    propertyType: 'Single Family Home',
    features: [
      'Open floor plan with hardwood floors throughout',
      'Gourmet kitchen with granite counters and island',
      'Primary suite with tray ceiling and en-suite bath',
      'Screened-in back porch',
      'Two-car garage',
      'Fenced backyard',
      'Tankless water heater',
      'HOA community pool and clubhouse',
    ],
    description:
      'Move-in ready gem in one of Charlotte\'s most sought-after neighborhoods. This beautifully maintained home offers an open floor plan with rich hardwood floors and abundant natural light. The kitchen is a standout with granite countertops, a large island, and stainless appliances open to the family room. The primary suite features a tray ceiling and spa-like bath with dual vanities. Enjoy Carolina evenings on the screened porch overlooking the private fenced yard. Top-rated schools, shopping, and dining all within minutes.',
    photos: [],
    listingAgent: 'Jennifer Walters',
    broker: 'Dickens Mitchener & Associates',
    mlsNumber: 'MLS3948127',
    sellingPoints: [
      'Move-in ready — nothing to do but unpack',
      'Award-winning Ballantyne schools district',
      'Minutes from Ballantyne Corporate Park for easy commuting',
      'Community pool and amenities included',
      'Rare screened porch perfect for year-round enjoyment',
    ],
  },
];

export const DEMO_PLATFORMS = ['instagram', 'facebook', 'googleAds'] as const;

export const ALL_PLATFORM_IDS: readonly PlatformId[] = [
  'instagram',
  'facebook',
  'googleAds',
  'twitter',
  'metaAd',
  'magazineFullPage',
  'magazineHalfPage',
  'postcard',
  'zillow',
  'realtorCom',
  'homesComTrulia',
  'mlsDescription',
] as const;
