import { MLSComplianceConfig, ProhibitedTerm } from '@/lib/types';

// --- Steering ---
const steeringTerms: ProhibitedTerm[] = [
  {
    term: 'exclusive neighborhood',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Implies racial or economic exclusion of protected classes',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'desirable location',
  },
  {
    term: 'exclusive area',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Implies exclusion based on protected class characteristics',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'sought-after area',
  },
  {
    term: 'exclusive community',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Suggests people are excluded from the community',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'well-established community',
  },
  {
    term: 'no crime',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Steers buyers based on racial demographics and crime stereotypes',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'peaceful setting',
  },
  {
    term: 'safe area',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Implies other areas are unsafe, often a proxy for racial composition',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'quiet area',
  },
  {
    term: 'safe neighborhood',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Neighborhood safety language is a proxy for racial steering',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'quiet neighborhood',
  },
  {
    term: 'low crime',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Crime-related language steers based on racial demographics',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'well-maintained area',
  },
  {
    term: 'crime-free',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Crime references in listings are proxies for racial composition',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'peaceful community',
  },
  {
    term: 'best schools',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'School quality references are proxies for racial composition',
    law: '42 U.S.C. § 3604(c); HUD advertising guidelines',
    suggestedAlternative: 'near schools',
  },
  {
    term: 'top-rated schools',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'School rating language steers based on racial demographics',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'close to schools',
  },
  {
    term: 'good schools',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'School quality language can be a proxy for neighborhood demographics',
    law: '42 U.S.C. § 3604(c); NAR guidelines',
    suggestedAlternative: 'near schools',
  },
  {
    term: 'integrated neighborhood',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'References to racial makeup of a neighborhood constitute steering',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'welcoming neighborhood',
  },
  {
    term: 'changing neighborhood',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Code for demographic shifts; constitutes racial steering',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'evolving community',
  },
  {
    term: 'desirable neighbors',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Implies selection of neighbors by protected characteristics',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'friendly community',
  },
  {
    term: 'nice neighbors',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Can imply preference for certain types of people',
    law: 'NAR Code of Ethics Article 10',
    suggestedAlternative: 'friendly community',
  },
  {
    term: 'prestigious area',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Can imply economic or racial exclusion',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'well-regarded area',
  },
  {
    term: 'up-and-coming neighborhood',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Often code for gentrifying area; implies demographic change',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'growing community',
  },
  {
    term: 'prestigious, exclusive neighborhood',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Code for racial/socioeconomic exclusion',
    law: '42 U.S.C. § 3604(a),(c)',
    suggestedAlternative: 'well-maintained neighborhood',
  },
  {
    term: 'safe, low-crime area',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Functions as coded racial language about neighborhoods',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'describe security features of property',
  },
  {
    term: 'top-rated schools nearby',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'School quality as proxy for racial composition',
    law: '42 U.S.C. § 3604(c); NAR guidance',
    suggestedAlternative: 'near schools',
  },
  {
    term: 'close-knit community where everyone knows each other',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Signals demographic homogeneity',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'active community association',
  },
  {
    term: 'established neighborhood with long-time residents',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Can imply resistance to demographic change',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'established neighborhood',
  },
  {
    term: 'good neighborhood',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Functions as demographic code',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'neighborhood',
  },
  {
    term: 'bad area',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Functions as demographic code',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'neighborhood',
  },
  {
    term: 'trump country',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Political affiliation used to describe an area',
    law: '42 U.S.C. § 3604(c) (steering proxy); NAR Code of Ethics Art. 10',
    suggestedAlternative: 'rural community',
  },
  {
    term: 'trump supporters welcome',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Explicit political preference',
    law: '42 U.S.C. § 3604(c) (steering proxy); NAR Code of Ethics Art. 10',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'maga community',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Explicit political identity marketing',
    law: '42 U.S.C. § 3604(c) (steering proxy); NAR Code of Ethics Art. 10',
    suggestedAlternative: 'remove entirely',
  },
];

// --- Familial Status ---
const familialStatusTerms: ProhibitedTerm[] = [
  {
    term: 'family neighborhood',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Suggests preference for families, excludes non-family households',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'welcoming community',
  },
  {
    term: 'family-friendly',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Implies preference for families with children over other household types',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'suitable for all',
  },
  {
    term: 'great for families',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Targets families and excludes other household compositions',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'spacious and versatile',
  },
  {
    term: 'perfect for families',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Explicitly targets families, excluding non-family households',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'ideal living space',
  },
  {
    term: 'ideal for kids',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Targets households with children, discriminates against those without',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'spacious living areas',
  },
  {
    term: 'no children',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Directly excludes families with children',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'quiet setting',
  },
  {
    term: 'adults only',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Excludes families with children unless qualifying as senior housing',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'quiet community',
  },
  {
    term: 'adult community',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Excludes families with children unless HOPA-qualified',
    law: '42 U.S.C. § 3604(c); HOPA',
    suggestedAlternative: 'established community',
  },
  {
    term: 'adult living',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Implies exclusion of children unless HOPA-qualified',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'comfortable living',
  },
  {
    term: 'perfect for couples',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Targets specific household composition, excludes others',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'cozy layout',
  },
  {
    term: 'empty nesters',
    category: 'familial-status',
    severity: 'soft',
    shortExplanation: 'Targets a specific life stage, may discourage families with children',
    law: '42 U.S.C. § 3604(c); NAR guidelines',
    suggestedAlternative: 'low-maintenance lifestyle',
  },
  {
    term: 'starter home',
    category: 'familial-status',
    severity: 'soft',
    shortExplanation: 'Targets specific life stage and may imply age or familial preference',
    law: 'NAR Code of Ethics Article 10',
    suggestedAlternative: 'charming home',
  },
  {
    term: 'playground nearby',
    category: 'familial-status',
    severity: 'soft',
    shortExplanation: 'Emphasizing child amenities can signal familial status preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'parks nearby',
  },
  {
    term: 'no kids',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Explicit exclusion of families',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'perfect for singles or couples',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Implies families with children unwelcome',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'one-bedroom apartment',
  },
  {
    term: 'ideal for mature adults',
    category: 'familial-status',
    severity: 'soft',
    shortExplanation: 'Signals children and families unwelcome',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'spacious unit with modern finishes',
  },
  {
    term: 'quiet adult living',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Combines age preference with child exclusion',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'quiet community',
  },
  {
    term: 'no kids allowed',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Explicit child exclusion',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'couples preferred',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Implies families not welcome',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'not suitable for children',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Direct discouragement of families',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'child-free environment',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Explicit exclusion of families',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'professional tenants only',
    category: 'familial-status',
    severity: 'soft',
    shortExplanation: 'Functions as proxy for "no children/families"',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'income requirements apply',
  },
  {
    term: 'seeking quiet, responsible tenants',
    category: 'familial-status',
    severity: 'soft',
    shortExplanation: '"Quiet" + "responsible" implies children unwelcome',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'well-maintained community',
  },
  {
    term: 'senior lifestyle community',
    category: 'familial-status',
    severity: 'hard',
    shortExplanation: 'Excludes families without legal basis (unless HOPA-qualified)',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'describe actual amenities',
  },
  {
    term: 'no play areas on property',
    category: 'familial-status',
    severity: 'soft',
    shortExplanation: 'Emphasizing absence of child amenities signals children unwelcome',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'describe amenities that exist',
  },
  {
    term: 'prefer tenants who work 9-5',
    category: 'familial-status',
    severity: 'soft',
    shortExplanation: 'Signals preference for childless adults',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'income requirements apply',
  },
  {
    term: 'limit 2 persons per unit',
    category: 'familial-status',
    severity: 'soft',
    shortExplanation: 'May disproportionately affect families (depends on unit size)',
    law: '42 U.S.C. § 3604(c); Keating Memo',
    suggestedAlternative: 'occupancy based on unit size per HUD guidelines',
  },
];

// --- Disability ---
const disabilityTerms: ProhibitedTerm[] = [
  {
    term: 'handicapped',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Outdated and offensive term for people with disabilities',
    law: '42 U.S.C. § 3604(c); 42 U.S.C. § 3604(f)',
    suggestedAlternative: 'accessible',
  },
  {
    term: 'crippled',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Derogatory language toward people with disabilities',
    law: '42 U.S.C. § 3604(f)',
    suggestedAlternative: 'accessible',
  },
  {
    term: 'able-bodied only',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Directly excludes people with physical disabilities',
    law: '42 U.S.C. § 3604(f)',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'must be able to climb stairs',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Excludes people with mobility impairments',
    law: '42 U.S.C. § 3604(f)',
    suggestedAlternative: 'multi-level home',
  },
  {
    term: 'no wheelchairs',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Directly discriminates against wheelchair users',
    law: '42 U.S.C. § 3604(f)',
    suggestedAlternative: 'limited accessibility features',
  },
  {
    term: 'not suitable for disabled',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Discourages people with disabilities from applying',
    law: '42 U.S.C. § 3604(f)',
    suggestedAlternative: 'contact agent for accessibility details',
  },
  {
    term: 'no mental illness',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Excludes people with mental health disabilities',
    law: '42 U.S.C. § 3604(f)',
    suggestedAlternative: 'all applicants welcome',
  },
  {
    term: 'physically fit tenants',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Implies physical ability is a requirement for occupancy',
    law: '42 U.S.C. § 3604(f)',
    suggestedAlternative: 'all are welcome',
  },
  {
    term: 'no group homes',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Group homes for disabled persons are protected under FHA',
    law: '42 U.S.C. § 3604(f); Olmstead v. L.C.',
    suggestedAlternative: 'single-family residence',
  },
  {
    term: 'walking distance',
    category: 'disability',
    severity: 'soft',
    shortExplanation: 'Assumes ambulatory ability; may discourage disabled applicants',
    law: '42 U.S.C. § 3604(f); NAR guidelines',
    suggestedAlternative: 'nearby',
  },
  {
    term: 'not suitable for handicapped',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Direct discriminatory statement',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no mentally ill tenants',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Explicit mental disability exclusion',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'perfect for the physically fit',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Implies disabled persons unwelcome',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'near trails and outdoor recreation',
  },
  {
    term: 'no blind or deaf tenants',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Explicit sensory disability exclusion',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'healthy tenants preferred',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Implies persons with illness/disability not desired',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no service animals, no exceptions',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Forecloses reasonable accommodation',
    law: '42 U.S.C. § 3604(f)(3)(B)',
    suggestedAlternative: 'pet policy: please inquire',
  },
  {
    term: 'drug-free community',
    category: 'disability',
    severity: 'soft',
    shortExplanation: 'May discourage protected recovering addicts',
    law: '42 U.S.C. § 3604(f)',
    suggestedAlternative: 'remove from advertising',
  },
  {
    term: 'must be self-sufficient',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Implies persons needing accommodation unwelcome',
    law: '42 U.S.C. § 3604(f)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no crazy people',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Stigmatizing mental health exclusion',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'seeking tenants in good physical condition',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Describes desired physical attributes',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'normal tenants only',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Implies disabled persons are abnormal',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'not for those with mobility issues',
    category: 'disability',
    severity: 'hard',
    shortExplanation: 'Adds discriminatory advice to factual description',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'third-floor walk-up',
  },
  {
    term: 'absolutely no pets, no exceptions',
    category: 'disability',
    severity: 'soft',
    shortExplanation: 'Signals unwillingness to accommodate service animals',
    law: '42 U.S.C. § 3604(f)(3)(B)',
    suggestedAlternative: 'pet policy applies — inquire for details',
  },
];

// --- Race, Color, National Origin ---
const raceColorNationalOriginTerms: ProhibitedTerm[] = [
  {
    term: 'white neighborhood',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Describes neighborhood by racial composition',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'established neighborhood',
  },
  {
    term: 'black neighborhood',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Describes neighborhood by racial composition',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'vibrant neighborhood',
  },
  {
    term: 'ethnic neighborhood',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'References ethnicity to describe an area',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'diverse neighborhood',
  },
  {
    term: 'no minorities',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Explicitly excludes racial or ethnic minorities',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'whites only',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Explicit racial discrimination',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'open to all',
  },
  {
    term: 'english speakers only',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Language restrictions are a proxy for national origin discrimination',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'all are welcome',
  },
  {
    term: 'no immigrants',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Discriminates based on national origin',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'all applicants welcome',
  },
  {
    term: 'american only',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Discriminates based on national origin or citizenship',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'open to all qualified applicants',
  },
  {
    term: 'speaks english',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Language requirements are national origin discrimination',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'all are welcome',
  },
  {
    term: 'ethnic food nearby',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Using ethnic descriptions signals racial makeup of area',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'diverse dining options nearby',
  },
  {
    term: 'predominantly white',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Describes demographic composition of a neighborhood',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'describe the actual characteristic',
  },
  {
    term: 'predominantly black',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Describes demographic composition of a neighborhood',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'describe the actual characteristic',
  },
  {
    term: 'predominantly hispanic',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Describes demographic composition of a neighborhood',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'describe the actual characteristic',
  },
  {
    term: 'caucasian community',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Explicitly identifies racial composition',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'well-maintained community',
  },
  {
    term: 'colored home',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Racial descriptor of property',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'updated home',
  },
  {
    term: 'black area',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Racial descriptor of neighborhood',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'neighborhood',
  },
  {
    term: 'prefer light-skinned',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Explicit color-based preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'diverse community',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Directly references racial/ethnic makeup',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'neighborhood',
  },
  {
    term: 'restricted community',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Historically associated with racial covenants',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove or describe specific restriction type',
  },
  {
    term: 'restricted neighborhood',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Historically associated with racial covenants',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove or describe specific restriction type',
  },
  {
    term: 'urban neighborhood',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Commonly understood racial code word when describing demographics',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'downtown location',
  },
  {
    term: 'urban area',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Commonly understood racial code word when describing demographics',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'downtown location',
  },
  {
    term: 'inner-city',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Commonly understood racial code word',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'downtown location',
  },
  {
    term: 'traditional neighborhood',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Can signal racial homogeneity',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'established neighborhood',
  },
  {
    term: 'must speak english',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Language-based national origin discrimination',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'american-born preferred',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Explicit national origin preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'hispanic area',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Ethnic demographics as neighborhood descriptor',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'neighborhood',
  },
  {
    term: 'asian community',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Ethnic demographics as neighborhood descriptor',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'neighborhood',
  },
  {
    term: 'citizens only',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Functions as national origin proxy',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no section 8',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Disparate impact on race; illegal in many jurisdictions',
    law: '42 U.S.C. § 3604(c) (disparate impact theory)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'traditional american neighborhood',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Code for white, native-born residents',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'established neighborhood',
  },
  {
    term: 'near ethnic restaurants',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Describes neighborhood demographics through cultural references',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'near dining and shopping',
  },
  {
    term: 'American heritage community',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Code for racial/ethnic exclusion',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'historic community',
  },
];

// --- Religion ---
const religionTerms: ProhibitedTerm[] = [
  {
    term: 'walking distance to church',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Shows religious preference; discourages non-Christian applicants',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'near places of worship',
  },
  {
    term: 'christian community',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Describes area by religious affiliation; excludes non-Christians',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'welcoming community',
  },
  {
    term: 'jewish neighborhood',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Describes area by religious affiliation',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'established neighborhood',
  },
  {
    term: 'muslim area',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Describes area by religious affiliation',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'diverse community',
  },
  {
    term: 'no religious',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Excludes people based on religious practice',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'church-going',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Implies religious practice as a qualification for housing',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'community-oriented',
  },
  {
    term: 'christian home',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Describes property in religious terms',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'updated home',
  },
  {
    term: 'jewish residence',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Religious descriptor of property',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'well-maintained residence',
  },
  {
    term: 'no muslims',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Explicit religious exclusion',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'catholic tenants preferred',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Explicit religious preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'near beautiful church',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Pairs religious landmark with religious preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'near houses of worship',
  },
  {
    term: 'perfect for devout families',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Expresses religious preference for occupants',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'temple district',
    category: 'religion',
    severity: 'soft',
    shortExplanation: 'Uses religious landmark to characterize area',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'neighborhood',
  },
  {
    term: 'faith-based community',
    category: 'religion',
    severity: 'soft',
    shortExplanation: 'Implies religious belief expected',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'active community',
  },
  {
    term: 'perfect for a god-fearing family',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Expresses religious preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'bible belt community values',
    category: 'religion',
    severity: 'soft',
    shortExplanation: 'Signals Christian preference',
    law: '42 U.S.C. § 3604(c); MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no atheists',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Explicit religious exclusion',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no scientologists',
    category: 'religion',
    severity: 'hard',
    shortExplanation: 'Explicit religious exclusion',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'christmas-loving neighborhood',
    category: 'religion',
    severity: 'soft',
    shortExplanation: 'Associates area with Christian celebration',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove from property description',
  },
];

// --- Sex/Gender ---
const sexGenderTerms: ProhibitedTerm[] = [
  {
    term: 'bachelor pad',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Targets single males, implies gender preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'modern living space',
  },
  {
    term: 'man cave',
    category: 'sex-gender',
    severity: 'soft',
    shortExplanation: 'Gendered language that targets male buyers',
    law: '42 U.S.C. § 3604(c); NAR guidelines',
    suggestedAlternative: 'bonus room',
  },
  {
    term: 'mother-in-law suite',
    category: 'sex-gender',
    severity: 'soft',
    shortExplanation: 'Gendered and familial language; industry moving away from this term',
    law: 'NAR Code of Ethics Article 10; industry best practices',
    suggestedAlternative: 'guest suite',
  },
  {
    term: 'master bedroom',
    category: 'sex-gender',
    severity: 'soft',
    shortExplanation: 'Term has problematic historical connotations; industry shifting away',
    law: 'NAR guidelines; MLS best practices',
    suggestedAlternative: 'primary bedroom',
  },
  {
    term: 'master bath',
    category: 'sex-gender',
    severity: 'soft',
    shortExplanation: 'Term has problematic historical connotations; industry shifting away',
    law: 'NAR guidelines; MLS best practices',
    suggestedAlternative: 'primary bathroom',
  },
  {
    term: 'female roommate',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Specifying gender of desired tenant is discriminatory',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'roommate wanted',
  },
  {
    term: 'male roommate',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Specifying gender of desired tenant is discriminatory',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'roommate wanted',
  },
  {
    term: 'ladies only',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Gender-based restriction on occupancy',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'men only',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Gender-based restriction on occupancy',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'no LGBT',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Discriminates based on sexual orientation and gender identity',
    law: '42 U.S.C. § 3604(c); Executive Order 13988 (2021)',
    suggestedAlternative: 'all are welcome',
  },
  {
    term: 'female tenants only',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Explicit sex-based preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'males preferred',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Explicit sex-based preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'perfect for a single woman',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Sex-based occupant preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'cozy one-bedroom apartment',
  },
  {
    term: 'she-shed',
    category: 'sex-gender',
    severity: 'soft',
    shortExplanation: 'Genders a property feature',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'studio or garden house',
  },
  {
    term: 'traditional families welcome',
    category: 'sex-gender',
    severity: 'soft',
    shortExplanation: 'Code excluding LGBTQ families',
    law: '42 U.S.C. § 3604(c); NAR Art. 10',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'straight tenants preferred',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Explicit sexual orientation discrimination',
    law: '42 U.S.C. § 3604(c); NAR Art. 10',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no transgenders',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Explicit gender identity discrimination',
    law: '42 U.S.C. § 3604(c); NAR Art. 10',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'normal couples only',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Implies non-heterosexual couples abnormal',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: "ladies' building",
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Explicit sex preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'his and hers closets',
    category: 'sex-gender',
    severity: 'soft',
    shortExplanation: 'Heteronormative assumption',
    law: 'NAR guidelines',
    suggestedAlternative: 'dual walk-in closets',
  },
  {
    term: 'looking for a good husband and wife',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Combines sex, marital status, and religious tone',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'bachelor apartment for one',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Implies preference for unmarried men; discriminates on sex and marital status',
    law: 'MCA § 49-2-305 (sex, marital status)',
    suggestedAlternative: 'studio apartment',
  },
  {
    term: 'no pregnant women',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Montana expands sex protection to include pregnancy and maternity',
    law: 'MCA § 49-2-305 (sex/maternity)',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'not suitable during pregnancy',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Discriminatory exclusion based on pregnancy status',
    law: 'MCA § 49-2-305 (sex/maternity)',
    suggestedAlternative: 'remove from ad',
  },
  {
    term: 'expecting mothers only',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Restricts housing to specific pregnancy/parental status',
    law: 'MCA § 49-2-305 (sex/maternity)',
    suggestedAlternative: 'all welcome',
  },
];

// --- Age (Montana-specific) ---
const ageTerms: ProhibitedTerm[] = [
  {
    term: 'young professionals',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets a specific age group, excluding older applicants',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'working professionals',
  },
  {
    term: 'perfect for millennials',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets a specific generation, excludes others',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'modern lifestyle',
  },
  {
    term: 'retiree community',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets retirees and discourages younger applicants',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'established community',
  },
  {
    term: 'senior living',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Age-targeted language unless HOPA-qualified',
    law: 'MCA § 49-2-305; HOPA',
    suggestedAlternative: 'comfortable living',
  },
  {
    term: 'young couple',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets by age and familial status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'any buyer',
  },
  {
    term: 'no elderly',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Directly excludes older individuals',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'youthful neighborhood',
    category: 'age',
    severity: 'soft',
    shortExplanation: 'Implies the area is for younger people',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'vibrant neighborhood',
  },
  {
    term: 'mature community',
    category: 'age',
    severity: 'soft',
    shortExplanation: 'Implies the area is for older residents',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'established community',
  },
  {
    term: 'retirees welcome',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Age-based preference',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'describe property features',
  },
  {
    term: 'no college students',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets specific age group',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'income and credit requirements apply',
  },
  {
    term: 'mature, responsible tenants',
    category: 'age',
    severity: 'soft',
    shortExplanation: '"Mature" functions as age descriptor',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'qualified applicants welcome',
  },
  {
    term: 'seeking tenants aged 30-50',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Explicit age range restriction',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'active lifestyle',
    category: 'age',
    severity: 'soft',
    shortExplanation: 'Can function as age discrimination',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'near trails and outdoor recreation',
  },
  {
    term: 'great starter home for twentysomethings',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets specific age group',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'affordable entry-level home',
  },
  {
    term: 'working adults preferred',
    category: 'age',
    severity: 'soft',
    shortExplanation: 'Excludes retirees and younger people',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'income requirements apply',
  },
  {
    term: 'retired couples only',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Excludes non-retired and non-coupled applicants based on age and marital status',
    law: 'MCA § 49-2-305 (age)',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'must be 25 or older to apply',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Explicit age restriction in housing',
    law: 'MCA § 49-2-305 (age)',
    suggestedAlternative: 'remove age requirement',
  },
  {
    term: 'recently retired? this is your dream home',
    category: 'age',
    severity: 'soft',
    shortExplanation: 'Targets specific age demographic',
    law: 'MCA § 49-2-305 (age)',
    suggestedAlternative: 'peaceful retreat for all',
  },
];

// --- Marital Status (Montana-specific) ---
const maritalStatusTerms: ProhibitedTerm[] = [
  {
    term: 'married couples only',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Restricts housing based on marital status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'all applicants welcome',
  },
  {
    term: 'newlyweds',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Targets by marital status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'all buyers',
  },
  {
    term: 'ideal for single',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Targets a specific marital status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'efficient layout',
  },
  {
    term: 'no unmarried couples',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Directly discriminates based on marital status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'divorced',
    category: 'marital-status',
    severity: 'soft',
    shortExplanation: 'References marital status in housing advertising',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove reference to marital status',
  },
  {
    term: 'singles only',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Marital status restriction',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'one-bedroom apartment',
  },
  {
    term: 'traditional family home',
    category: 'marital-status',
    severity: 'soft',
    shortExplanation: 'Code for married heterosexual couple',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'four-bedroom home',
  },
  {
    term: 'must be married to apply',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Explicit marital status requirement',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'couples only',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Romantic partnership requirement',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no roommates',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Can function as marital status discrimination',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'perfect for newlyweds',
    category: 'marital-status',
    severity: 'soft',
    shortExplanation: 'Targets specific marital status + age',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'charming two-bedroom home',
  },
  {
    term: 'spouse required on lease',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Assumes/requires married status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'all occupants must be on lease',
  },
  {
    term: 'stable family household required',
    category: 'marital-status',
    severity: 'soft',
    shortExplanation: 'Implies married couple preference',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'income and credit requirements apply',
  },
];

// --- Creed (Montana-specific) ---
const creedTerms: ProhibitedTerm[] = [
  {
    term: 'conservative neighborhood',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Describes area by political leaning; discriminates on political beliefs (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'established neighborhood',
  },
  {
    term: 'liberal community',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Describes area by political leaning (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'diverse community',
  },
  {
    term: 'blue state values',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Political affiliation used to describe area character',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'community values',
  },
  {
    term: 'red state living',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Political affiliation used to describe area character',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'quality of life',
  },
  {
    term: 'like-minded neighbors',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Can imply political or ideological homogeneity (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'friendly neighbors',
  },
  {
    term: 'red state values',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Political identity marketing',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'blue state haven',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Political identity marketing',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'patriotic community',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Politically coded language',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove from property ads',
  },
  {
    term: 'faith-and-flag community',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Combines religious + political creed (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'active community',
  },
  {
    term: 'freedom-loving homesteaders',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Appeals to political-philosophical identity',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'acreage with off-grid features',
  },
  {
    term: 'eco-conscious residents only',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Creed requirement for housing (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'energy-efficient home with solar panels',
  },
  {
    term: 'traditional Montana values',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Implies creed/worldview requirement for housing (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305 (creed)',
    suggestedAlternative: 'welcoming community',
  },
  {
    term: 'shared values community',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Implies ideological conformity requirement',
    law: 'MCA § 49-2-305 (creed)',
    suggestedAlternative: 'active community',
  },
  {
    term: 'no political signs allowed',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Restricting political expression may implicate creed protections',
    law: 'MCA § 49-2-305 (creed)',
    suggestedAlternative: 'remove from property advertising',
  },
];

// --- Economic Exclusion ---
const economicExclusionTerms: ProhibitedTerm[] = [
  {
    term: 'no vouchers',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Refusing housing vouchers is discriminatory in many jurisdictions',
    law: '42 U.S.C. § 3604(c) (disparate impact theory)',
    suggestedAlternative: 'income verification required',
  },
  {
    term: 'executive home',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Can imply economic exclusion of lower-income groups',
    law: 'NAR Code of Ethics Article 10',
    suggestedAlternative: 'luxury home',
  },
  {
    term: 'upscale clientele',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Implies economic requirements for residents',
    law: 'NAR Code of Ethics Article 10',
    suggestedAlternative: 'refined living',
  },
  {
    term: 'exclusive listing',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Can imply economic or social exclusion',
    law: 'NAR Code of Ethics Article 10',
    suggestedAlternative: 'featured listing',
  },
  {
    term: 'high-class area',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Class-based language implies economic exclusion',
    law: '42 U.S.C. § 3604(c); NAR guidelines',
    suggestedAlternative: 'premium location',
  },
  {
    term: 'affluent area',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Describes area by wealth level; may exclude lower-income applicants',
    law: 'NAR Code of Ethics Article 10',
    suggestedAlternative: 'sought-after location',
  },
  {
    term: 'wealthy neighborhood',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Describes area by economic status of residents',
    law: 'NAR Code of Ethics Article 10',
    suggestedAlternative: 'desirable neighborhood',
  },
  {
    term: 'executive housing',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Economic exclusion; potential racial proxy',
    law: 'NAR guidelines; disparate impact theory',
    suggestedAlternative: 'spacious home with premium finishes',
  },
  {
    term: 'upper-class neighborhood',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Socioeconomic + racial implications',
    law: 'Disparate impact; NAR Art. 10',
    suggestedAlternative: 'well-maintained neighborhood',
  },
  {
    term: 'no vouchers accepted',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Same impact as "No Section 8"',
    law: 'Disparate impact; local ordinances',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'high-income earners only',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Economic exclusion',
    law: 'Disparate impact theory',
    suggestedAlternative: 'income requirements: 3x monthly rent',
  },
  {
    term: 'affluent community',
    category: 'economic-exclusion',
    severity: 'soft',
    shortExplanation: 'Socioeconomic demographics',
    law: 'Disparate impact; NAR guidelines',
    suggestedAlternative: 'neighborhood',
  },
];

// --- Misleading Claims ---
const misleadingClaimsTerms: ProhibitedTerm[] = [
  {
    term: 'guaranteed appreciation',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Property values cannot be guaranteed; misleads buyers',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'strong market area',
  },
  {
    term: 'sure investment',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'No real estate investment is guaranteed; misleading claim',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'promising opportunity',
  },
  {
    term: 'guaranteed return',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Returns on real estate cannot be guaranteed',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'potential for growth',
  },
  {
    term: 'will appreciate',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Future appreciation cannot be promised',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'historically strong area',
  },
  {
    term: 'can only go up',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Property values can decrease; false guarantee',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'desirable market',
  },
  {
    term: 'risk-free investment',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'All investments carry risk; misleading to claim otherwise',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'investment opportunity',
  },
  {
    term: 'best deal',
    category: 'misleading-claims',
    severity: 'soft',
    shortExplanation: 'Superlative claims are difficult to substantiate',
    law: 'FTC Act §5; NAR guidelines',
    suggestedAlternative: 'great value',
  },
  {
    term: 'lowest price',
    category: 'misleading-claims',
    severity: 'soft',
    shortExplanation: 'Comparative price claims must be verifiable',
    law: 'FTC Act §5; NAR guidelines',
    suggestedAlternative: 'competitively priced',
  },
  {
    term: 'below market value',
    category: 'misleading-claims',
    severity: 'soft',
    shortExplanation: 'Market value claims should be substantiated',
    law: 'FTC Act §5; NAR guidelines',
    suggestedAlternative: 'priced to sell',
  },
  {
    term: 'completely renovated',
    category: 'misleading-claims',
    severity: 'soft',
    shortExplanation: 'Misrepresentation of property condition when only partial',
    law: 'FTC Act § 5; NAR Art. 12',
    suggestedAlternative: 'updated kitchen and bathrooms',
  },
  {
    term: 'waterfront',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Deceptive property description if no water access. Only flag if property is not actually waterfront',
    law: 'FTC Act § 5; NAR Art. 12',
    suggestedAlternative: 'water views',
  },
  {
    term: 'award-winning schools',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Unsubstantiated claim',
    law: 'FTC Act § 5; NAR Art. 12',
    suggestedAlternative: 'near schools',
  },
  {
    term: 'minutes from downtown',
    category: 'misleading-claims',
    severity: 'soft',
    shortExplanation: 'Misleading proximity claim',
    law: 'FTC Act § 5; NAR Art. 12',
    suggestedAlternative: 'miles from downtown',
  },
  {
    term: 'will not last',
    category: 'misleading-claims',
    severity: 'soft',
    shortExplanation: 'False urgency',
    law: 'FTC Act § 5; NAR Art. 12',
    suggestedAlternative: 'available now',
  },
  {
    term: 'no HOA',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Misleading omission if HOA exists',
    law: 'FTC Act § 5',
    suggestedAlternative: 'HOA details available on request',
  },
  {
    term: 'brand new',
    category: 'misleading-claims',
    severity: 'soft',
    shortExplanation: 'Misrepresentation if built 3+ years ago. Only flag if property is not actually new construction',
    law: 'FTC Act § 5; NAR Art. 12',
    suggestedAlternative: 'built in [year]',
  },
];

// Combine all terms
const allProhibitedTerms: ProhibitedTerm[] = [
  ...steeringTerms,
  ...familialStatusTerms,
  ...disabilityTerms,
  ...raceColorNationalOriginTerms,
  ...religionTerms,
  ...sexGenderTerms,
  ...ageTerms,
  ...maritalStatusTerms,
  ...creedTerms,
  ...economicExclusionTerms,
  ...misleadingClaimsTerms,
];

export const montanaCompliance: MLSComplianceConfig = {
  state: 'Montana',
  mlsName: 'Montana Regional MLS',
  lastUpdated: '2026-02-15',
  version: '2.0',
  rules: [
    'Must include listing broker name',
    'Must include MLS number if available',
    'No guaranteed or promised appreciation language',
    'Must disclose if property is in a flood zone (if known)',
    'Fair housing compliance required',
    'No discriminatory language per Fair Housing Act',
    '48-hour listing entry deadline for new listings and status changes (excludes weekends/holidays)',
    'Clear Cooperation Policy: publicly marketed listings must be entered within 1 business day',
    'Internet ads must include licensee identification on every viewable page or linked (ARM 24.210.430)',
    'Material changes must be updated within 7 days (ARM 24.210.430)',
    'Must display creation date and last-update date on web advertising (ARM 24.210.430)',
  ],
  requiredDisclosures: [
    'Listing courtesy of [Broker Name]',
    'Information deemed reliable but not guaranteed',
    'Equal Housing Opportunity',
  ],
  prohibitedTerms: allProhibitedTerms,
  maxDescriptionLength: 1000, // Conservative default — verify against actual Montana MLS limits
  docPaths: {
    federal: [
      'compliance-docs/federal/fair-housing-overview.md',
      'compliance-docs/federal/steering.md',
      'compliance-docs/federal/familial-status.md',
      'compliance-docs/federal/disability.md',
      'compliance-docs/federal/race-color-national-origin.md',
      'compliance-docs/federal/religion.md',
      'compliance-docs/federal/sex-gender.md',
      'compliance-docs/federal/advertising-rules.md',
    ],
    state: [
      'compliance-docs/state/montana/human-rights-act.md',
      'compliance-docs/state/montana/age-protections.md',
      'compliance-docs/state/montana/marital-status.md',
      'compliance-docs/state/montana/creed.md',
    ],
    industry: [
      'compliance-docs/industry/nar-ethics-guidelines.md',
      'compliance-docs/industry/common-pitfalls.md',
    ],
  },
};

