import { MLSComplianceConfig, ProhibitedTerm } from '@/lib/types';
import { allFederalTerms } from './federal';

// =============================================================================
// Montana-specific terms (not covered by federal)
// Montana Human Rights Act (MCA § 49-2-305) adds: age, marital status, creed
// Montana also has sex/gender expansions (pregnancy/maternity) and state-specific
// misleading claims citing Montana MLS Rules.
// =============================================================================

// --- Sex/Gender additions (Montana pregnancy/maternity expansions) ---
const montanaSexGenderTerms: ProhibitedTerm[] = [
  {
    term: 'bachelor apartment for one',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Implies preference for unmarried men; discriminates on sex and marital status',
    law: 'MCA § 49-2-305 (sex, marital status)',
    suggestedAlternative: 'studio apartment',
  },
  {
    term: 'no pregnant women',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Montana expands sex protection to include pregnancy and maternity',
    law: 'MCA § 49-2-305 (sex/maternity)',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'not suitable during pregnancy',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Discriminatory exclusion based on pregnancy status',
    law: 'MCA § 49-2-305 (sex/maternity)',
    suggestedAlternative: 'remove from ad',
  },
  {
    term: 'expecting mothers only',
    category: 'sex-gender',
    severity: 'hard',
    shortExplanation: 'Restricts housing to specific pregnancy/parental status',
    law: 'MCA § 49-2-305 (sex/maternity)',
    suggestedAlternative: 'all welcome',
  },
];

// --- Religion addition (Montana-specific law citation) ---
const montanaReligionTerms: ProhibitedTerm[] = [
  {
    term: 'bible belt community values',
    category: 'religion',
    severity: 'soft',
    shortExplanation: 'Signals Christian preference',
    law: '42 U.S.C. § 3604(c); MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
];

// --- Age (Montana-specific: MCA § 49-2-305) ---
const ageTerms: ProhibitedTerm[] = [
  {
    term: 'young professionals',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets a specific age group, excluding older applicants',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'working professionals',
  },
  {
    term: 'perfect for millennials',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets a specific generation, excludes others',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'modern lifestyle',
  },
  {
    term: 'retiree community',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets retirees and discourages younger applicants',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'established community',
  },
  {
    term: 'senior living',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Age-targeted language unless HOPA-qualified',
    law: 'MCA § 49-2-305; HOPA',
    suggestedAlternative: 'comfortable living',
  },
  {
    term: 'young couple',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets by age and familial status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'any buyer',
  },
  {
    term: 'no elderly',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Directly excludes older individuals',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'youthful neighborhood',
    category: 'age',
    severity: 'soft',
    shortExplanation: 'Implies the area is for younger people',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'vibrant neighborhood',
  },
  {
    term: 'mature community',
    category: 'age',
    severity: 'soft',
    shortExplanation: 'Implies the area is for older residents',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'established community',
  },
  {
    term: 'retirees welcome',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Age-based preference',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'describe property features',
  },
  {
    term: 'no college students',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets specific age group',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'income and credit requirements apply',
  },
  {
    term: 'mature, responsible tenants',
    category: 'age',
    severity: 'soft',
    shortExplanation: '"Mature" functions as age descriptor',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'qualified applicants welcome',
  },
  {
    term: 'seeking tenants aged 30-50',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Explicit age range restriction',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'active lifestyle',
    category: 'age',
    severity: 'soft',
    shortExplanation: 'Can function as age discrimination',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'near trails and outdoor recreation',
  },
  {
    term: 'great starter home for twentysomethings',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Targets specific age group',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'affordable entry-level home',
  },
  {
    term: 'working adults preferred',
    category: 'age',
    severity: 'soft',
    shortExplanation: 'Excludes retirees and younger people',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'income requirements apply',
  },
  {
    term: 'retired couples only',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Excludes non-retired and non-coupled applicants based on age and marital status',
    law: 'MCA § 49-2-305 (age)',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'must be 25 or older to apply',
    category: 'age',
    severity: 'hard',
    shortExplanation: 'Explicit age restriction in housing',
    law: 'MCA § 49-2-305 (age)',
    suggestedAlternative: 'remove age requirement',
  },
  {
    term: 'recently retired? this is your dream home',
    category: 'age',
    severity: 'soft',
    shortExplanation: 'Targets specific age demographic',
    law: 'MCA § 49-2-305 (age)',
    suggestedAlternative: 'peaceful retreat for all',
  },
];

// --- Marital Status (Montana-specific: MCA § 49-2-305) ---
const maritalStatusTerms: ProhibitedTerm[] = [
  {
    term: 'married couples only',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Restricts housing based on marital status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'all applicants welcome',
  },
  {
    term: 'newlyweds',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Targets by marital status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'all buyers',
  },
  {
    term: 'ideal for single',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Targets a specific marital status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'efficient layout',
  },
  {
    term: 'no unmarried couples',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Directly discriminates based on marital status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'divorced',
    category: 'marital-status',
    severity: 'soft',
    shortExplanation: 'References marital status in housing advertising',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove reference to marital status',
  },
  {
    term: 'singles only',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Marital status restriction',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'one-bedroom apartment',
  },
  {
    term: 'traditional family home',
    category: 'marital-status',
    severity: 'soft',
    shortExplanation: 'Code for married heterosexual couple',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'four-bedroom home',
  },
  {
    term: 'must be married to apply',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Explicit marital status requirement',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'couples only',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Romantic partnership requirement',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no roommates',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Can function as marital status discrimination',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'perfect for newlyweds',
    category: 'marital-status',
    severity: 'soft',
    shortExplanation: 'Targets specific marital status + age',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'charming two-bedroom home',
  },
  {
    term: 'spouse required on lease',
    category: 'marital-status',
    severity: 'hard',
    shortExplanation: 'Assumes/requires married status',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'all occupants must be on lease',
  },
  {
    term: 'stable family household required',
    category: 'marital-status',
    severity: 'soft',
    shortExplanation: 'Implies married couple preference',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'income and credit requirements apply',
  },
];

// --- Creed (Montana-specific: MCA § 49-2-305) ---
const creedTerms: ProhibitedTerm[] = [
  {
    term: 'conservative neighborhood',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Describes area by political leaning; discriminates on political beliefs (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'established neighborhood',
  },
  {
    term: 'liberal community',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Describes area by political leaning (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'diverse community',
  },
  {
    term: 'blue state values',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Political affiliation used to describe area character',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'community values',
  },
  {
    term: 'red state living',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Political affiliation used to describe area character',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'quality of life',
  },
  {
    term: 'like-minded neighbors',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Can imply political or ideological homogeneity (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'friendly neighbors',
  },
  {
    term: 'red state values',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Political identity marketing',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'blue state haven',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Political identity marketing',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'patriotic community',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Politically coded language',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'remove from property ads',
  },
  {
    term: 'faith-and-flag community',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Combines religious + political creed (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'active community',
  },
  {
    term: 'freedom-loving homesteaders',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Appeals to political-philosophical identity',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'acreage with off-grid features',
  },
  {
    term: 'eco-conscious residents only',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Creed requirement for housing (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305',
    suggestedAlternative: 'energy-efficient home with solar panels',
  },
  {
    term: 'traditional Montana values',
    category: 'creed',
    severity: 'hard',
    shortExplanation: 'Implies creed/worldview requirement for housing (conservative compliance interpretation — creed coverage of political worldview is not explicitly established in MT housing case law)',
    law: 'MCA § 49-2-305 (creed)',
    suggestedAlternative: 'welcoming community',
  },
  {
    term: 'shared values community',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Implies ideological conformity requirement',
    law: 'MCA § 49-2-305 (creed)',
    suggestedAlternative: 'active community',
  },
  {
    term: 'no political signs allowed',
    category: 'creed',
    severity: 'soft',
    shortExplanation: 'Restricting political expression may implicate creed protections',
    law: 'MCA § 49-2-305 (creed)',
    suggestedAlternative: 'remove from property advertising',
  },
];

// --- Misleading Claims (Montana-specific: cite Montana MLS Rules) ---
const montanaMisleadingClaimsTerms: ProhibitedTerm[] = [
  {
    term: 'guaranteed appreciation',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Property values cannot be guaranteed; misleads buyers',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'strong market area',
  },
  {
    term: 'sure investment',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'No real estate investment is guaranteed; misleading claim',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'promising opportunity',
  },
  {
    term: 'guaranteed return',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Returns on real estate cannot be guaranteed',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'potential for growth',
  },
  {
    term: 'will appreciate',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Future appreciation cannot be promised',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'historically strong area',
  },
  {
    term: 'can only go up',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Property values can decrease; false guarantee',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'desirable market',
  },
  {
    term: 'risk-free investment',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'All investments carry risk; misleading to claim otherwise',
    law: 'Montana MLS Rules; FTC Act §5',
    suggestedAlternative: 'investment opportunity',
  },
];

// Combine all Montana-specific terms with federal terms
const allProhibitedTerms: ProhibitedTerm[] = [
  ...allFederalTerms,
  ...montanaSexGenderTerms,
  ...montanaReligionTerms,
  ...ageTerms,
  ...maritalStatusTerms,
  ...creedTerms,
  ...montanaMisleadingClaimsTerms,
];

export const montanaCompliance: MLSComplianceConfig = {
  state: 'Montana',
  mlsName: 'Montana Regional MLS',
  lastUpdated: '2026-02-15',
  version: '2.0',
  rules: [
    'Must include listing broker name',
    'Must include MLS number if available',
    'No guaranteed or promised appreciation language',
    'Must disclose if property is in a flood zone (if known)',
    'Fair housing compliance required',
    'No discriminatory language per Fair Housing Act',
    '48-hour listing entry deadline for new listings and status changes (excludes weekends/holidays)',
    'Clear Cooperation Policy: publicly marketed listings must be entered within 1 business day',
    'Internet ads must include licensee identification on every viewable page or linked (ARM 24.210.430)',
    'Material changes must be updated within 7 days (ARM 24.210.430)',
    'Must display creation date and last-update date on web advertising (ARM 24.210.430)',
  ],
  requiredDisclosures: [
    'Listing courtesy of [Broker Name]',
    'Information deemed reliable but not guaranteed',
    'Equal Housing Opportunity',
  ],
  prohibitedTerms: allProhibitedTerms,
  maxDescriptionLength: 1000, // Conservative default — verify against actual Montana MLS limits
  docPaths: {
    federal: [
      'compliance-docs/federal/fair-housing-overview.md',
      'compliance-docs/federal/steering.md',
      'compliance-docs/federal/familial-status.md',
      'compliance-docs/federal/disability.md',
      'compliance-docs/federal/race-color-national-origin.md',
      'compliance-docs/federal/religion.md',
      'compliance-docs/federal/sex-gender.md',
      'compliance-docs/federal/advertising-rules.md',
    ],
    state: [
      'compliance-docs/state/montana/human-rights-act.md',
      'compliance-docs/state/montana/age-protections.md',
      'compliance-docs/state/montana/marital-status.md',
      'compliance-docs/state/montana/creed.md',
    ],
    industry: [
      'compliance-docs/industry/nar-ethics-guidelines.md',
      'compliance-docs/industry/common-pitfalls.md',
    ],
  },
};
