import { MLSComplianceConfig, ProhibitedTerm } from '@/lib/types';
import { allFederalTerms } from './federal';

// =============================================================================
// Ohio-specific terms (not covered by federal)
// Ohio Revised Code (ORC) §4112.02(H) adds: military status, ancestry
// Ohio also has state-specific steering, misleading claims (ORC §4735.18),
// and NAR Settlement 2024 terms.
// =============================================================================

// --- Steering additions (Ohio-specific) ---
const ohioSteeringTerms: ProhibitedTerm[] = [
  {
    term: 'board approval',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'HOA review process can facilitate discriminatory screening',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'HOA review process',
  },
  {
    term: 'membership approval',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'Application process can be used discriminatorily',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'application process',
  },
  {
    term: 'board approval required',
    category: 'steering',
    severity: 'hard',
    shortExplanation: 'HOA review process can facilitate discriminatory screening',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'HOA review process',
  },
  {
    term: 'private',
    category: 'steering',
    severity: 'soft',
    shortExplanation: 'Can imply exclusion from gated community',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'gated',
  },
];

// --- Race/Ancestry additions (Ohio-specific: ORC §4112.02(H)) ---
const ohioRaceAncestryTerms: ProhibitedTerm[] = [
  {
    term: 'Appalachian area',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Ancestry-based descriptor of neighborhood demographics',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'neighborhood',
  },
  {
    term: 'no Appalachians',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Explicit ancestry-based exclusion',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'hillbilly neighborhood',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Derogatory ancestry-based descriptor',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'old-country charm',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Ancestry and national origin coded language',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'charming character',
  },
  {
    term: 'heritage community',
    category: 'race-color-national-origin',
    severity: 'hard',
    shortExplanation: 'Ancestry-based descriptor of community character',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'established community',
  },
  {
    term: 'Appalachian',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Ancestry-based descriptor when used to describe people or area',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'describe property features',
  },
  {
    term: 'ethnic heritage neighborhood',
    category: 'race-color-national-origin',
    severity: 'soft',
    shortExplanation: 'Ancestry and ethnicity-based descriptor',
    law: 'ORC §4112.02(H)(7)',
    suggestedAlternative: 'neighborhood',
  },
];

// --- Religion addition (Ohio-specific: different law citation than MT) ---
const ohioReligionTerms: ProhibitedTerm[] = [
  {
    term: 'bible belt community values',
    category: 'religion',
    severity: 'soft',
    shortExplanation: 'Signals Christian preference',
    law: '42 U.S.C. § 3604(c)',
    suggestedAlternative: 'remove entirely',
  },
];

// --- Misleading Claims (Ohio-specific: cite ORC §4735.18 and ORC §1345) ---
const ohioMisleadingClaimsTerms: ProhibitedTerm[] = [
  {
    term: 'guaranteed appreciation',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Property values cannot be guaranteed; misleads buyers',
    law: 'ORC §4735.18; FTC Act §5',
    suggestedAlternative: 'strong market area',
  },
  {
    term: 'sure investment',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'No real estate investment is guaranteed; misleading claim',
    law: 'ORC §4735.18; FTC Act §5',
    suggestedAlternative: 'promising opportunity',
  },
  {
    term: 'guaranteed return',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Returns on real estate cannot be guaranteed',
    law: 'ORC §4735.18; FTC Act §5',
    suggestedAlternative: 'potential for growth',
  },
  {
    term: 'will appreciate',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Future appreciation cannot be promised',
    law: 'ORC §4735.18; FTC Act §5',
    suggestedAlternative: 'historically strong area',
  },
  {
    term: 'can only go up',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Property values can decrease; false guarantee',
    law: 'ORC §4735.18; FTC Act §5',
    suggestedAlternative: 'desirable market',
  },
  {
    term: 'risk-free investment',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'All investments carry risk; misleading to claim otherwise',
    law: 'ORC §4735.18; FTC Act §5',
    suggestedAlternative: 'investment opportunity',
  },
  {
    term: 'guaranteed sale',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Cannot guarantee property sale outcomes',
    law: 'ORC §4735.18',
    suggestedAlternative: 'marketing services included',
  },
  {
    term: 'we guarantee',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Absolute guarantees about real estate outcomes prohibited',
    law: 'ORC §4735.18',
    suggestedAlternative: 'we are committed to',
  },
  {
    term: 'guaranteed closing',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Cannot guarantee transaction closings',
    law: 'ORC §4735.18',
    suggestedAlternative: 'smooth transaction process',
  },
  {
    term: 'no commission',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Misleading fee disclosure; must disclose actual compensation structure',
    law: 'ORC §4735.18',
    suggestedAlternative: 'disclose actual fee structure',
  },
  {
    term: 'free home evaluation',
    category: 'misleading-claims',
    severity: 'soft',
    shortExplanation: 'Potentially misleading consumer advertising claim',
    law: 'ORC §1345',
    suggestedAlternative: 'complimentary market analysis',
  },
  // NAR Settlement 2024 terms
  {
    term: 'free buyer representation',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Post-NAR Settlement 2024: buyer representation fees must be disclosed',
    law: 'NAR Settlement 2024',
    suggestedAlternative: 'buyer representation available',
  },
  {
    term: 'no cost to buyer',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Post-NAR Settlement 2024: cannot advertise buyer services as "free"',
    law: 'NAR Settlement 2024',
    suggestedAlternative: 'buyer consultation available',
  },
  {
    term: 'buyer pays nothing',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Post-NAR Settlement 2024: misleading fee disclosure',
    law: 'NAR Settlement 2024',
    suggestedAlternative: 'contact agent for details',
  },
  {
    term: 'our services are free',
    category: 'misleading-claims',
    severity: 'hard',
    shortExplanation: 'Post-NAR Settlement 2024: all compensation must be disclosed',
    law: 'NAR Settlement 2024',
    suggestedAlternative: 'contact agent for details',
  },
];

// --- Military Status (Ohio-specific: ORC §4112.02(H)) ---
const militaryStatusTerms: ProhibitedTerm[] = [
  {
    term: 'no veterans',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Explicit exclusion based on military service status',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'all applicants welcome',
  },
  {
    term: 'no military',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Direct exclusion based on military status',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'all applicants welcome',
  },
  {
    term: 'civilian tenants only',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Excludes service members and veterans',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'all welcome',
  },
  {
    term: 'no active duty',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Excludes active military service members',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'all applicants welcome',
  },
  {
    term: 'military not welcome',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Direct discriminatory statement against military members',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no National Guard',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Excludes National Guard members',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'all applicants welcome',
  },
  {
    term: 'no reservists',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Excludes military reserve members',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'all applicants welcome',
  },
  {
    term: 'perfect for military families',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Targets specific protected class; implies preference',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'spacious family home',
  },
  {
    term: 'civilian tenants preferred',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Expresses preference against military status',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no deployments',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Discriminates against active duty military who may deploy',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'stable income required',
  },
  {
    term: 'non-military preferred',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Explicit preference against military status',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'military families not preferred',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Direct discriminatory preference statement',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'remove entirely',
  },
  {
    term: 'no military housing allowance',
    category: 'military-status',
    severity: 'hard',
    shortExplanation: 'Refuses legitimate military income source',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'income requirements apply',
  },
  {
    term: 'military housing',
    category: 'military-status',
    severity: 'soft',
    shortExplanation: 'Targets military members; may discourage civilian applicants',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'near base amenities',
  },
  {
    term: 'near military base',
    category: 'military-status',
    severity: 'soft',
    shortExplanation: 'Can signal military status preference',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'convenient location',
  },
  {
    term: 'veteran community',
    category: 'military-status',
    severity: 'soft',
    shortExplanation: 'Describes area by military status demographics',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'neighborhood',
  },
  {
    term: 'military community',
    category: 'military-status',
    severity: 'soft',
    shortExplanation: 'Describes area by military status demographics',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'neighborhood',
  },
  {
    term: 'military town',
    category: 'military-status',
    severity: 'soft',
    shortExplanation: 'Characterizes area by military demographics',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'describe actual amenities',
  },
  {
    term: 'veteran housing',
    category: 'military-status',
    severity: 'soft',
    shortExplanation: 'Targets specific protected class',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'affordable housing',
  },
  {
    term: 'military discount',
    category: 'military-status',
    severity: 'soft',
    shortExplanation: 'While well-intentioned, can signal military status preference',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'inquire about available programs',
  },
  {
    term: 'veteran-friendly',
    category: 'military-status',
    severity: 'soft',
    shortExplanation: 'Implies military status consideration in housing decisions',
    law: 'ORC §4112.02(H)',
    suggestedAlternative: 'welcoming community',
  },
];

// Combine all Ohio-specific terms with federal terms
const allProhibitedTerms: ProhibitedTerm[] = [
  ...allFederalTerms,
  ...ohioSteeringTerms,
  ...ohioRaceAncestryTerms,
  ...ohioReligionTerms,
  ...ohioMisleadingClaimsTerms,
  ...militaryStatusTerms,
];

export const ohioCompliance: MLSComplianceConfig = {
  state: 'Ohio',
  mlsName: 'Ohio MLS (multi-board)',
  lastUpdated: '2026-02-15',
  version: '1.0',
  rules: [
    'Must display license number in all advertising (ORC §4735.16)',
    'Must include registered brokerage name with equal or greater prominence (ORC §4735.16)',
    'Team name must not appear more prominent than brokerage name (OAC 1301:5-1-02)',
    'Internet ads must include licensee identification on every viewable page (OAC 1301:5-1-02(G))',
    'No guaranteed or promised appreciation language (ORC §4735.18)',
    'Fair housing compliance required (ORC §4112.02)',
    'Must disclose if property is in a flood zone (if known)',
    'Listing information must be updated within 14 days of material changes',
  ],
  requiredDisclosures: [
    'Listing courtesy of [Broker Name]',
    'Information deemed reliable but not guaranteed',
    'Equal Housing Opportunity',
    'License # [number] (ORC §4735.16)',
  ],
  prohibitedTerms: allProhibitedTerms,
  maxDescriptionLength: 1500,
  docPaths: {
    federal: [
      'compliance-docs/federal/fair-housing-overview.md',
      'compliance-docs/federal/steering.md',
      'compliance-docs/federal/familial-status.md',
      'compliance-docs/federal/disability.md',
      'compliance-docs/federal/race-color-national-origin.md',
      'compliance-docs/federal/religion.md',
      'compliance-docs/federal/sex-gender.md',
      'compliance-docs/federal/advertising-rules.md',
    ],
    state: [
      'compliance-docs/state/ohio/ohio-revised-code-4735.md',
      'compliance-docs/state/ohio/ohio-civil-rights-4112.md',
      'compliance-docs/state/ohio/ohio-military-status.md',
      'compliance-docs/state/ohio/ohio-team-advertising.md',
    ],
    industry: [
      'compliance-docs/industry/nar-ethics-guidelines.md',
      'compliance-docs/industry/common-pitfalls.md',
    ],
  },
};
